---
podman-build:
  image: quay.io/podman/stable
  stage: build
  script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - podman build -t "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME " .
    - podman push "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME"
  when: manual
...
